"""Send summary emails via SMTP."""

import logging
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

import config

logger = logging.getLogger(__name__)


def _markdown_to_html(md: str) -> str:
    """Minimal markdown-to-HTML conversion for email rendering."""
    import re

    html = md

    # Escape HTML entities first
    html = html.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")

    # Headers
    html = re.sub(r"^### (.+)$", r"<h3>\1</h3>", html, flags=re.MULTILINE)
    html = re.sub(r"^## (.+)$", r"<h2>\1</h2>", html, flags=re.MULTILINE)
    html = re.sub(r"^# (.+)$", r"<h1>\1</h1>", html, flags=re.MULTILINE)

    # Bold
    html = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", html)

    # Bullet points
    html = re.sub(r"^- (.+)$", r"<li>\1</li>", html, flags=re.MULTILINE)

    # Wrap consecutive <li> in <ul>
    html = re.sub(
        r"((?:<li>.*?</li>\n?)+)",
        r"<ul>\1</ul>",
        html,
    )

    # Line breaks for remaining plain lines
    html = re.sub(r"\n\n", r"<br><br>", html)

    return html


def send_summary_email(
    video_title: str, video_id: str, summaries: dict[str, str], channel: str
) -> None:
    """Send an email with summaries in all configured languages."""
    video_url = f"https://www.youtube.com/watch?v={video_id}"

    msg = MIMEMultipart("alternative")
    msg["Subject"] = f"[@{channel}] New Stock Analysis: {video_title}"
    msg["From"] = config.SENDER_EMAIL
    msg["To"] = config.RECIPIENT_EMAIL

    # Build plain text — all languages separated by dividers
    text_parts = [
        f"New video from @{channel}\n"
        f"Title: {video_title}\n"
        f"Link: {video_url}\n"
    ]
    for lang, summary in summaries.items():
        text_parts.append(f"\n{'='*60}\n{lang}\n{'='*60}\n\n{summary}")
    text_body = "\n".join(text_parts)

    # Build HTML — all languages in one email with section dividers
    summary_html_parts = []
    for lang, summary in summaries.items():
        summary_html_parts.append(
            f'<div style="background: #f0f0f5; padding: 8px 16px; margin: 20px 0 10px 0; '
            f'border-radius: 4px; font-weight: bold; font-size: 16px;">{lang}</div>\n'
            f'{_markdown_to_html(summary)}'
        )
    summaries_html = "\n<hr style='border: 2px solid #e94560; margin: 30px 0;'>\n".join(
        summary_html_parts
    )

    html_body = f"""\
<html>
<body style="font-family: Arial, sans-serif; max-width: 800px; margin: 0 auto; padding: 20px;">
  <div style="background: #1a1a2e; color: white; padding: 20px; border-radius: 8px 8px 0 0;">
    <h1 style="margin: 0; font-size: 18px;">New Stock Analysis Video</h1>
    <p style="margin: 8px 0 0 0; color: #ccc;">from @{channel}</p>
  </div>
  <div style="border: 1px solid #ddd; border-top: none; padding: 20px; border-radius: 0 0 8px 8px;">
    <h2 style="margin-top: 0;">
      <a href="{video_url}" style="color: #e94560; text-decoration: none;">{video_title}</a>
    </h2>
    <hr style="border: 1px solid #eee;">
    {summaries_html}
    <hr style="border: 1px solid #eee;">
    <p style="color: #888; font-size: 12px;">
      Generated by YouTube Stock Summarizer | LLM: {config.LLM_PROVIDER}
    </p>
  </div>
</body>
</html>"""

    msg.attach(MIMEText(text_body, "plain"))
    msg.attach(MIMEText(html_body, "html"))

    logger.info("Sending email to %s", config.RECIPIENT_EMAIL)

    with smtplib.SMTP(config.SMTP_SERVER, config.SMTP_PORT) as server:
        server.starttls()
        server.login(config.SENDER_EMAIL, config.SENDER_PASSWORD)
        server.sendmail(config.SENDER_EMAIL, config.RECIPIENT_EMAIL, msg.as_string())

    logger.info("Email sent successfully")
